### ISSUE TITLE
Strange new lines that possibly should be cleaned up

### ISSUE THREAD

**Issue by Ainali** [Kyrkosok/database#3]
In the end of the text in http://kyrksok.se/church.html?church=12573080 there is strange new lines. In [the source](http://www.bebyggelseregistret.raa.se/bbr2/anlaggning/visaHistorik.raa?page=historik&visaHistorik=true&anlaggningId=21300000003890) there are also new lines but it does not render on the same way. Could it be cleaned up so not to have the blank line?

**Comment by Abbe98** [comment]
I would say that this is a case that should be reported to RAÄ, the issue lies within their data quality and hiding such issues would not benefit them. The same issue appears in Kringla.

**Comment by Abbe98** [comment]
Closing, as I'm unlikely to spend time on patching data quality issues. 

The "Anmärk" feature should be the way to move forward.
